name = "entity-framework"
title = "Entity Framework"
toc_landing_pages = [
    "/fundamentals/configure",
    #"/fundamentals/crud",
    #"/usage-examples",
    #"/fundamentals",
]

intersphinx = [
    "https://www.mongodb.com/docs/manual/objects.inv",
    "https://www.mongodb.com/docs/drivers/objects.inv",
    "https://www.mongodb.com/docs/atlas/objects.inv",
]
sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
provider-long = "MongoDB Entity Framework Core Provider"
provider-short = "Entity Framework Core Provider"
csharp-driver-long = "MongoDB .NET/C# Driver"
csharp-driver-short = ".NET/C# Driver"
framework = "Entity Framework"
framework-core = "{+framework+} Core"
framework-version = "7.0"
language = "C#"
language-dotnet = ".NET"
dotnet-csharp = ".NET/C#"
mongo-community = "MongoDB Community Edition"
mongo-enterprise = "MongoDB Enterprise Edition"
docs-branch = "master"                                   # always set this to the docs branch (i.e. master, 1.7, 1.8, etc.)
version-number = "7.0"                                   # always set this to the driver branch (i.e. 1.7.0, 1.8.0, etc.)
version = "v{+version-number+}"
stable-api = "Stable API"
bool-data-type = "``boolean``"
string-data-type = "``string``"
int-data-type = "``integer``"
not-available = "N/A"
package = "MongoDB.EntityFrameworkCore"
